Set wshShell =wscript.CreateObject("WScript.Shell")
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
wscript.sleep 300
wshshell.sendkeys "{SCROLLLOCK}"
